# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='message',
            new_name='content',
        ),
    ]
