# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170628_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='industry',
            field=models.CharField(default='tech', max_length=255),
            preserve_default=False,
        ),
    ]
