# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170629_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liability',
            old_name='acquired_at',
            new_name='incurred_at',
        ),
    ]
