# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20170630_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='liability',
            old_name='amount',
            new_name='value',
        ),
    ]
