# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20170630_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liability',
            name='accDepreciation',
        ),
    ]
